//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webapi
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
    public partial class listItem
    {
        public int itemid { get; set; }
        public int listid { get; set; }
        public Nullable<System.DateTime> updatedon { get; set; }
        public string Itemname { get; set; }
    
        public virtual listTable listTable { get; set; }
    }
}
